language: cpp
dist: trusty
os: linux
cache: apt
script:
  - docker build --build-arg BRANCH=$TRAVIS_BRANCH -t seahorn/clam-llvm10:latest -f docker/clam.Dockerfile .
  
  - 'if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
        docker push seahorn/clam-llvm10:latest;       
       fi '
       
services:
  - docker
install: true
notifications:
   slack: seahornteam:NAUqZmZHFFviPH4ktQbJXgKu
   email:
     recipients:
     - seahorn-build@googlegroups.com
     on_success: always
     on_failure: always
